name: simple_id
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3
  file_picker: ^5.5.0
  equatable: ^2.0.0
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.0
  rxdart: ^0.27.7
  get_it: ^7.6.4
  http: ^1.1.0
  lint: ^2.0.0
  bloc: ^8.1.2
  uuid: ^3.0.7
  image_cropper: ^5.0.0
  dotted_border: ^2.1.0
  image_picker: ^1.0.4
  pinput: ^3.0.1
  screenshot: ^2.1.0
  image: ^4.1.3
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - config/

